### ISSUE TITLE
ADC values not responding

### ISSUE THREAD

**Issue by DanHca** [electricimp/LIS3DH#15]
Can you confirm that you have got readings using the following line:
        accel.enableADC(true);
        local reading = accel.readADC(LIS3DH_ADC1);
which returns a constant value
   ADC1 = 1.40078
   ACD2 = 1.00234
   ACD3 = 0.801563
regardless of what I connect the pin to for input.  I would have expect that at least connecting ADC1 to GND would have resulted in a change.  I see references to bit 7 BDU needing to be set (but think that is done as part of enableADC?  The Hz seem fine but if you have any other guidance or sample code, it would be appreciated.

Thank you for what you have already provide and I hope to soon make even more use of the LIS3DH.

PS> The accel data is received fine so I know the basics are good.

**Comment by betzrhodes** [comment]
The ADC of the LIS3DH is effectively reuse of the internal ADC in the part used for reading the temperature sensor and its performance is quite limited.

The datasheet spec for the input range is 1200mV +/- 400mV, thus the part may only read voltages between 800mV and 1600mV. Also there is not a specified source impedance, but probably needs to be under 10Kohm.

In our tests its performance significantly lags that of the STM32 in the imp001-004m
